server:
  port: 8090

spring:
  neo4j:
    authentication:
      username: neo4j
      password: 12345678
    uri: bolt://localhost:7687
  cassandra:
    contact-points: 127.0.0.1:9042
    local-datacenter: datacenter1
  ai:
    openai:
      base-url: ${api.uri}
      api-key: ${api.sk}
      chat:
        options:
          model: deepseek-chat
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma3:12b
      embedding:
        model: lrs33/bce-embedding-base_v1:latest
        options:
          model: lrs33/bce-embedding-base_v1:latest
          num-batch: 512
          num-ctx: 512
    vectorstore:
      milvus:
        client:
          host: localhost
          port: 19530
          username: root
          password: Milvus
        databaseName: default
        collectionName: vector_store
        embeddingDimension: 1024
        indexType: IVF_FLAT
        metricType: COSINE
        initialize-schema: true
        auto-id: true
        id-field-name: doc_id
    chat:
      memory:
        cassandra:
          table: chat_history
          keyspace: another_domain_ai

searxng:
  base-url: http://localhost:8041


logging:
  level:
    org.springframework.ai: DEBUG
    reactor.core: TRACE
